<a href="https://colab.research.google.com/github/kuppamcharan0606/Credit-Card-Fraud-Detection-Using-LogisticRegression/blob/master/Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Installing dependencies

In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [14]:
#Load csv file to pandas dataframe
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [15]:
#First 5 rows
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [16]:
#Last 5 rows
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
69410,53411,1.106584,-0.925436,0.661483,-1.664040,-1.075488,0.235442,-1.022176,0.343909,1.810465,...,0.302333,0.839735,-0.195164,-0.615158,0.279175,0.151560,0.047940,0.019442,68.02,0.0
69411,53411,-1.009202,-0.429729,2.109263,-0.718647,-0.389684,-0.038644,0.089580,0.314820,0.790871,...,-0.021664,-0.168552,0.282626,0.111297,-0.492715,0.779755,0.023864,0.133686,105.13,0.0
69412,53411,1.194319,0.184864,0.380408,0.373276,-0.018658,0.005934,-0.078417,0.062905,-0.296652,...,-0.190932,-0.524439,0.103525,-0.295192,0.180030,0.124729,-0.012819,0.003846,3.58,0.0
69413,53411,0.898915,-0.209692,0.537196,1.562960,-0.747575,-0.824138,0.249155,-0.168179,0.248011,...,-0.103293,-0.539026,-0.064167,0.697779,0.414650,-0.532499,-0.002198,0.054169,154.42,0.0
69414,53411,1.356225,-0.322399,0.450949,-0.345147,-0.784041,-0.434317,-0.485366,-0.038548,-1.212064,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
#Dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69415 entries, 0 to 69414
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    69415 non-null  int64
 1   V1      69415 non-null  float64
 2   V2      69415 non-null  float64
 3   V3      69415 non-null  float64
 4   V4      69415 non-null  float64
 5   V5      69415 non-null  float64
 6   V6      69415 non-null  float64
 7   V7      69415 non-null  float64
 8   V8      69415 non-null  float64
 9   V9      69415 non-null  float64
 10  V10     69415 non-null  float64
 11  V11     69415 non-null  float64
 12  V12     69415 non-null  float64
 13  V13     69415 non-null  float64
 14  V14     69414 non-null  float64
 15  V15     69414 non-null  float64
 16  V16     69414 non-null  float64
 17  V17     69414 non-null  float64
 18  V18     69414 non-null  float64
 19  V19     69414 non-null  float64
 20  V20     69414 non-null  float64
 21  V21     69414 non-null  float64
 22  V22     69414 non-null  float64
 23  V23     69414 non-null  float64
 24  V24     69414 non-null  float64
 25  V25     69414 non-null  float64
 26  V26     69414 non-null  float64
 27  V27     69414 non-null  float64
 28  V28     69414 non-null  float64
 29  Amount  69414 non-null  float64
 30  Class   69414 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 16.4 MB

In [18]:
#Checking number of missing values in each column

credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [24]:
#Distribution of legit transaction and fraudlent transaction

credit_card_data['Class'].value_counts()

0.0    69241
1.0      173
Name: Class, dtype: int64

In [25]:
#seperating data for analysis

legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]
print(legit.shape)
print(fraud.shape)

(69241, 31)
(173, 31)

In [26]:
#Stastical measures of data

legit.Amount.describe()

count    69241.000000
mean        96.985632
std        271.371862
min          0.000000
25%          7.680000
50%         26.500000
75%         88.500000
max      19656.530000
Name: Amount, dtype: float64

In [27]:
fraud.Amount.describe()

count     173.00000
mean       95.72237
std       221.11352
min         0.00000
25%         1.00000
50%         7.58000
75%        99.99000
max      1809.68000
Name: Amount, dtype: float64

In [28]:
#Comparing the values of both the transactions

credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,34530.112737,-0.227869,-0.033289,0.706865,0.155935,-0.258839,0.107358,-0.097214,0.048905,0.030613,...,0.046047,-0.030834,-0.106006,-0.037728,0.006142,0.136117,0.021729,0.001667,0.003137,96.985632
1.0,30035.913295,-6.933421,5.000911,-9.340224,5.397284,-5.161426,-2.120226,-7.252875,3.426366,-3.228419,...,0.429221,0.836306,-0.201712,-0.245147,-0.072067,0.249135,0.109489,0.565158,0.041636,95.722370

Dealing with the Imbalanced Data

Undersampling :
We got number of fraudulent data = 173

In [29]:
legit_sample = legit.sample(n=173)

In [33]:
#Concatinate two data frames

new_dataset = pd.concat([legit_sample,fraud],axis = 0)
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
64460,51155,-11.205461,7.914633,-13.987752,4.333341,-8.484970,-3.506561,-8.935243,7.704449,-2.336584,...,0.942593,-0.987848,-0.279446,-0.027299,0.644344,-0.263078,1.084023,0.211933,99.99,1.0
68067,52814,-1.101847,-1.632441,0.901067,0.847753,-1.249091,0.654937,1.448868,0.023308,-0.136742,...,0.610654,0.835795,1.179955,-0.029091,-0.300896,0.699175,-0.336072,-0.177587,519.90,1.0
68320,52934,1.036639,0.407227,0.757706,3.161821,-0.568122,0.202181,-0.689804,0.411380,0.336769,...,-0.050108,0.123761,-0.132568,0.350231,0.507701,0.189621,0.061016,0.063141,0.76,1.0
68522,53031,0.206075,1.387360,-1.045287,4.228686,-1.647549,-0.180897,-2.943678,0.859156,-1.181743,...,0.469199,0.344930,-0.203799,0.376640,0.715485,0.226003,0.628545,0.319918,0.76,1.0
68633,53076,1.296231,0.417447,0.193963,0.901644,0.130531,-0.371634,0.158126,-0.202669,-0.079512,...,-0.112114,-0.220002,-0.121022,-0.440454,0.671540,-0.413518,0.032838,0.020600,1.18,1.0

In [35]:
new_dataset['Class'].value_counts()

0.0    173
1.0    173
Name: Class, dtype: int64

In [43]:
#Splitting the data into features and targets

x = new_dataset.drop(columns='Class',axis = 1)
y = new_dataset['Class']

#Splitting the data into training data and testing data

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, stratify = y, random_state = 2)
print(x.shape,x_train.shape,x_test.shape)

(346, 30) (276, 30) (70, 30)

In [48]:
#Model Training

model = LogisticRegression()

In [49]:
model.fit(x_train, y_train)

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Model Evaluation

Accuracy Score

In [52]:
#Accuracy on training data
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction,y_train)
print(training_data_accuracy)

0.9565217391304348

In [53]:
#Accuracy on testing data
x_test_prediction = model.predict(x_test)
testing_data_accuracy = accuracy_score(x_test_prediction,y_test)
print(testing_data_accuracy)

0.8857142857142857